##################   ESP Home
title: ESP Home
icon: mdi:developer-board
cards:

      - type: vertical-stack
        cards:

        - type: markdown
          content: >
              ## Розетки

        - type: custom:vertical-stack-in-card
          cards:
          - type: markdown
            content: >
               **Прихожая - Sonoff Basic - питание лампы**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.sonoff_uptime_custom
            - entity: sensor.sonoff_wi_fi_signal
              name: Сигнал wi-fi
            - entity: sensor.sonoff_firmware_version
              name: Прошивка
          - type: entities
            show_header_toggle: false
            entities:
            - entity: switch.sonoff_basic_relay
              name: Питание
              tap_action: toggle

        - type: custom:vertical-stack-in-card
          cards:
          - type: markdown
            content: >
               **Туалет - Sonoff mini - подсветка зеркала**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.02_sonoff_mini_uptime_custom
            - entity: sensor.02_sonoff_mini_wifi_signal
              name: Сигнал wi-fi
            - entity: sensor.02_sonoff_mini_firmware_version
              name: Прошивка
          - type: entities
            show_header_toggle: false
            entities:
            - entity: switch.02_sonoff_mini_relay
              name: Питание
              tap_action: toggle
    
        - type: custom:vertical-stack-in-card
          cards:
          - type: markdown
            content: >
               **Туалет - Sonoff Basic - вентилятор**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.02_sonoff_basic_uptime_custom
            - entity: sensor.02_sonoff_basic_wifi_signal
              name: Сигнал wi-fi
            - entity: sensor.02_sonoff_basic_firmware_version
              name: Прошивка
          - type: entities
            show_header_toggle: false
            entities:
            - entity: switch.02_sonoff_basic_relay
              name: Питание
              tap_action: toggle    
    
        - type: custom:vertical-stack-in-card
          cards:
          - type: markdown
            content: >
               **Детская А - Alfawise 8285, питание стола**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.08_alfawise_uptime_custom
            - entity: sensor.08_alfawise_wifi_signal
              name: Сигнал wi-fi
            - entity: sensor.08_alfawise_firmware_version
              name: Прошивка
          - type: entities
            show_header_toggle: false
            entities:
            - entity: switch.08_alfawise_relay
              name: Питание
              tap_action: toggle
              
      - type: vertical-stack
        cards:

        - type: markdown
          content: >
              ## Розетки - энергомониторы

        - type: custom:vertical-stack-in-card
          cards:
          - type: markdown
            content: >
               **Прачечная - Blitzwolf BW-SHP 2, стиральная машина**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.bwshp2_uptime_custom
            - entity: sensor.wi_fi_signal_bwshp2
              name: Сигнал wi-fi
            - entity: sensor.firmware_version_bwshp2
              name: Прошивка
          - type: entities
            show_header_toggle: false
            entities:
            - entity: switch.relay_bwshp2
              name: Питание
              tap_action: toggle
            - entity: switch.led_blue_bwshp2
              name: Синий светодиод
              tap_action: toggle
            - entity: switch.led_red_bwshp2
              name: Красный светодиод
              tap_action: toggle
            - entity: sensor.voltage_bwshp2
              name: Напряжение
            - entity: sensor.current_bwshp2
              name: Ток
            - entity: sensor.load_bwshp2
              name: Потребление
              

              
      - type: vertical-stack
        cards:

        - type: markdown
          content: >
              ## BLE Шлюзы
              
        - type: custom:vertical-stack-in-card
          cards:
          - type: markdown
            content: >
               **Кухня, ESP 32 BLE шлюз**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.kn_esp32_uptime_custom
            - entity: sensor.kn_esp32_wi_fi
              name: Сигнал wi-fi
            - entity: sensor.kn_esp32_firmware_version
              name: Прошивка
            - entity: switch.kn_esp32_restart
              name: Перезагрузка
              icon: mdi:reload
              
        - type: custom:vertical-stack-in-card
          cards:
          - type: markdown
            content: >
               **Гостиная, ESP 32 BLE шлюз**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.gg_esp32_uptime_custom
            - entity: sensor.gg_esp32_wi_fi
              name: Сигнал wi-fi
            - entity: sensor.gg_esp32_firmware_version
              name: Прошивка
            - entity: switch.gg_esp32_restart
              name: Перезагрузка
              icon: mdi:reload

        - type: custom:vertical-stack-in-card
          cards:
          - type: markdown
            content: >
               **Детская Д, ESP 32 BLE шлюз**
          - type: entities
            show_header_toggle: false
            entities:
            - entity: sensor.dd_esp32_uptime_custom
            - entity: sensor.dd_esp32_wi_fi
              name: Сигнал wi-fi
            - entity: sensor.dd_esp32_firmware_version
              name: Прошивка
            - entity: switch.dd_esp32_restart
              name: Перезагрузка
              icon: mdi:reload