##################   Автоматика
title: Вся автоматика
icon: mdi:script
cards:
    
      - type: vertical-stack
        cards:
        
          - type: markdown
            content: >
                **Автоматизации**

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              show_header_toggle: false
            filter:
              include:
               - domain: automation
              exclude:
               - state: 'off'

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              show_header_toggle: false
            filter:
              include:
               - domain: automation
              exclude:
               - state: 'on'
               
      - type: vertical-stack
        cards:
        
          - type: markdown
            content: >
                **Скрипты**

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              show_header_toggle: false
            filter:
              include:
               - domain: script
              sort:
                 method: entity_id  
               
      - type: vertical-stack
        cards:
        
          - type: markdown
            content: >
                **Группы**

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              show_header_toggle: false
            filter:
              include:
               - domain: group