# Имя устройства, будет подставляться по тексту конфига
substitutions:
  plug_name: 02_sonoff_basic
  
esphome:
  name: 02_sonoff_basic
  platform: ESP8266
  board: esp01_1m

# Параметры сети
wifi:
  ssid: 'имя сети'
  password: 'пароль'
  manual_ip:
    static_ip: 192.168.0.хх
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Логирование
logger:

# Активация Home Assistant API
api:
  password: 'пароль'

ota:
  password: 'пароль'

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${plug_name}_button
    on_press:
      - switch.toggle: relay
    
switch:
  - platform: gpio
    name: ${plug_name}_relay
    pin: GPIO12
    id: relay
    
sensor:
  - platform: uptime
    name: ${plug_name}_uptime

  - platform: wifi_signal
    name: ${plug_name}_wifi_signal
    update_interval: 60s

text_sensor:
  - platform: version
    name: ${plug_name}_firmware_version

