# Имя устройства, будет подставляться по тексту конфига
substitutions:
  plug_name: 02_sonoff_mini

esphome:
  name: 02_sonoff_mini
  platform: ESP8266
  board: esp01_1m

# Параметры сети
wifi:
  ssid: 'имя сети'
  password: 'пароль'
  manual_ip:
    static_ip: 192.168.0.хх
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Логирование
logger:

# Активация Home Assistant API
api:
  password: 'пароль'

ota:
  password: 'пароль'

# web_server:
#   port: 80
  
status_led:
  pin:
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle: 
          id: relay

  - platform: gpio
    name: ${plug_name}_sw
    pin: GPIO04
    id: switch_1
    on_press:
      then:
        - switch.toggle:
            id: relay
    on_release:
      then:
        - switch.toggle:
            id: relay

switch:
  - platform: gpio
    name: ${plug_name}_relay
    pin: GPIO12
    id: relay
    
sensor:
  - platform: uptime
    name: ${plug_name}_uptime

  - platform: wifi_signal
    name: ${plug_name}_wifi_signal
    update_interval: 60s

text_sensor:
  - platform: version
    name: ${plug_name}_firmware_version