- alias: 00_ilife_a4
  initial_state: true
  trigger:
    platform: time
    at: '10:00:00'
  condition:
  - condition: time
    weekday:
      - mon
      - wed
      - fri
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: xiaomi_aqara.play_ringtone
    data:
      gw_mac: 34:CE:00:88:B0:39
      ringtone_id: 10001
      ringtone_vol: 50
  - delay: 00:00:05
  - service: xiaomi_aqara.stop_ringtone
    data:
      gw_mac: 34:CE:00:88:B0:39   
  - service: notify.telegram
    data:
      title: 'Пылесос'
      message: "Робот пылесос вышел на тропу войны {{ states('sensor.time_date') }}"
  - service: switch.toggle
    entity_id: switch.ilifea4
    
- alias: 05_usb_cool_work
  initial_state: true
  trigger:
    platform: time
    at: '07:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.02_sonoff_basic_relay
    
- alias: 05_usb_cool_week
  initial_state: true
  trigger:
    platform: time
    at: '10:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.02_sonoff_basic_relay
    
- alias: 05_usb_cool_off
  initial_state: true
  trigger:
    platform: time
    at: '22:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.02_sonoff_basic_relay