- alias: 00_ilife_a4
  initial_state: true
  trigger:
    platform: time
    at: '10:00:00'
  condition:
  - condition: time
    weekday:
      - mon
      - wed
      - fri
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.ilife_a4
    
- alias: 05_usb_cool_on
  initial_state: true
  trigger:
   - platform: state
     entity_id: binary_sensor.day_work
     to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.02_sonoff_basic_relay
    
- alias: 05_usb_cool_off
  initial_state: true
  trigger:
   - platform: state
     entity_id: binary_sensor.day_work
     to: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.02_sonoff_basic_relay