## Включение увлажнения
- alias: 07_dd_hum_auto_on
  initial_state: true
#   initial_state: false
## ТРИГГЕР !!!
  trigger:
## Проверка каждые 3 минуты
   - platform: time_pattern
     minutes: '/3'
## УСЛОВИЯ !!!
  condition:
## Увлажнитель выключен
     - condition: state
       entity_id: switch.plug_158d000114a1e1
       state: 'off'
## Влажность ниже 45 %
     - condition: numeric_state
       entity_id: sensor.humidity_158d000156e92e
       below: 45
## Комплексный сенсор для увлажнения
     - condition: state
       entity_id: binary_sensor.07_dd_hum
       state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.plug_158d000114a1e1

## Выключение увлажнения    
- alias: 07_dd_hum_auto_off
  initial_state: true
#   initial_state: false
  trigger:
## Комплексный сенсор для увлажнения
   - platform: state
     entity_id: binary_sensor.07_dd_hum
     to: 'off'
  condition:
## Увлажнитель включен
     - condition: state
       entity_id: switch.plug_158d000114a1e1
       state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.plug_158d000114a1e1
    
## Предупреждение о недостатке воды
- alias: 07_dd_hum_water_warning
  initial_state: true
#   initial_state: false
  trigger:
## Падение мощности менее 10 Ватт
   - platform: numeric_state
     entity_id: sensor.load_158d000114a1e1
     below: 10
  condition:
## Увлажнитель включен
     - condition: state
       entity_id: switch.plug_158d000114a1e1
       state: 'on'
## Время работы
     - condition: time
       after: '08:00:00'
       before: '21:59:00'
  action:
    - service: notify.telegram
      data:
        title: 'Отчет'
        message: "Детская Д, в увлажнителе кончилась вода, или он отключен вручную, время - {{ states('sensor.time_date') }}"