## Включение увлажнения
- alias: 08_da_hum_auto_on
  initial_state: true
## ТРИГГЕР !!!
  trigger:
## Проверка каждые 3 минуты
   - platform: time_pattern
     minutes: '/3'
## УСЛОВИЯ !!!
  condition:
## Увлажнитель выключен
     - condition: state
       entity_id: switch.plug_158d00010ec4b8
       state: 'off'
## Влажность ниже 45 %
     - condition: numeric_state
       entity_id: sensor.humidity_158d000159c7e6
       below: 45
## Комплексный сенсор для увлажнения
     - condition: state
       entity_id: binary_sensor.08_da_hum
       state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.plug_158d00010ec4b8
    
    
## Выключение увлажнения
- alias: 08_da_hum_auto_off
  initial_state: true
  trigger:
## Комплексный сенсор для увлажнения
   - platform: state
     entity_id: binary_sensor.08_da_hum
     to: 'off'
  condition:
## Увлажнитель включен
     - condition: state
       entity_id: switch.plug_158d00010ec4b8
       state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.plug_158d00010ec4b8

## Предупреждение о недостатке воды    
- alias: 08_da_hum_water_warning
  initial_state: true
  trigger:
## Падение мощности менее 10 Ватт
   - platform: numeric_state
     entity_id: sensor.load_158d00010ec4b8
     below: 10
     for:
       minutes: 1
  condition:
## Увлажнитель включен
     - condition: state
       entity_id: switch.plug_158d00010ec4b8
       state: 'on'
## Время работы 
     - condition: state
       entity_id: binary_sensor.day_work
       state: 'on'
  action:
   - service: mqtt.publish
     data_template:
        topic: "states/error"
        payload_template: '080'
        retain: true