- alias: 911_reserve_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.reserve_state
   to: 'unavailable'
  action:
    - service: script.turn_on
      entity_id: script.mqtt_payload_reserve_offline

- alias: 911_reserve_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.reserve_state
   from: 'unavailable'
  action:
    - service: script.turn_on
      entity_id: script.mqtt_payload_reserve_online

- alias: 911_scenario_on
  initial_state: true
  trigger:
   - platform: state
     entity_id: sensor.reserve_scenario_group
     to: 'off'
   - platform: state
     entity_id: sensor.reserve_scenario_group
     to: 'unavailable'
  condition:
    - condition: state
      entity_id: group.scenario
      state: 'off'     
  action:
    - service: notify.telegram
      data:
        message: "Бытовые сценарии резервном сервере, Khadas VIM 2 отключены в - {{ states('sensor.time_date') }} . Включение сценариев на основном сервере"
    - service: homeassistant.turn_on
      entity_id:
         - group.scenario

- alias: 911_mqtt_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.mqtt_state
   to: 'unavailable'
  action:
    - service: notify.telegram
      data:
        message: "Потеря связи с MQTT сервером, Orange PI PC 2 - {{ states('sensor.time_date') }} ."

- alias: 911_mqtt_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.mqtt_state
   from: 'unavailable'
  action:
    - service: notify.telegram
      data:
        message: "Связь с MQTT сервером, Orange PI PC 2 восстановлена в - {{ states('sensor.time_date') }} ."
        
- alias: 911_test_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.rasp3b_state
   to: 'unavailable'
  action:
     - service: mqtt.publish
       data_template:
         topic: "states/test/system/test_offline"
         payload: '{{(states.sensor.time_date.state)}}'
         retain: true
     - service: mqtt.publish
       data_template:
         topic: "states/error"
         payload_template: '005'
         retain: true  

- alias: 911_test_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.rasp3b_state
   from: 'unavailable'
  action:
     - service: mqtt.publish
       data_template:
         topic: "states/test/system/test_online"
         payload: '{{(states.sensor.time_date.state)}}'
         retain: true
     - service: mqtt.publish
       data_template:
         topic: "states/error"
         payload_template: '006'
         retain: true  