# Полное освещение 
- alias: test_smart_light_on
  initial_state: true
  trigger:
# Одинарный клик на кнопку
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001e8a244
      click_type: single
  condition:
  - condition: state
    entity_id: light.24730816ecfabc996804
    state: 'off'
  action:
  - service: light.turn_on
    entity_id:
      - light.24730816ecfabc996804
    data_template:
       brightness: 255
       color_temp: 182

# Подсветка 
- alias: test2_smart_light_on
  initial_state: true
  trigger:
# Двойной клик на кнопку
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001e8a244
      click_type: double
  condition:
  - condition: state
    entity_id: light.24730816ecfabc996804
    state: 'off'
  action:
  - service: light.turn_on
    entity_id:
      - light.24730816ecfabc996804
    data_template:
       brightness: 45
       color_temp: 1000
       
# Освещение выкл
- alias: test_smart_light_off
  initial_state: true
  trigger:
# Одинарный клик на кнопку
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001e8a244
      click_type: single
# Двойной клик на кнопку
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001e8a244
      click_type: double
  condition:
  - condition: state
    entity_id: light.24730816ecfabc996804
    state: 'on'
  action:
  - service: light.turn_off
    entity_id:
      - light.24730816ecfabc996804
      
