- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /
    
- platform: filesize
  file_paths:
     - /config/home-assistant_v2.db
    
- platform: command_line
  name: cpu_temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'

- platform: rest
  resource: http://192.168.0.71:8123/api/states/sensor.online_custom?api_password=qwerty
  name: orange2_state
  force_update: true
  value_template: '{{ value_json.state }}'
  
- platform: rest
  resource: http://192.168.0.73:8123/api/states/sensor.online_custom?api_password=qwerty
  name: khadas_state
  force_update: true
  value_template: '{{ value_json.state }}'

